TuMvcApp/Models/ErrorViewModel.cs
using System;

namespace TuMvcApp.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

TuMvcApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TuMvcApp/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
	[Route("auth")]
	public class AuthController : Controller
	{
		[Route("signin")]
		public IActionResult signin(string returnUrl = null)
		{
			//return Challenge(new AuthenticationProperties { RedirectUri = returnUrl ?? "/home" });
			return Redirect("~/home");
		}
	}
}

TuMvcApp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }

        // GET: Categories/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        //// POST: Categories/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Categories/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Categories/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Categories/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Categories/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

TuMvcApp/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TuMvcApp.Controllers
{
    public class CoursesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


		// GET: Courses/Create
		public IActionResult Create()
		{
			return View();
		}

		// GET: Courses/Catalog
		public IActionResult Catalog()
		{
			return View();
		}

		// GET: Courses/Search
		public IActionResult Search(string q)
		{
			return View();
		}
	}
}

TuMvcApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TuMvcApp.Models;

namespace Tu_Mvc.Controllers
{
	public class HomeController : Controller
	{
		
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult About()
		{
			ViewData["Message"] = "Your application description page.";

			return View();
		}

		public IActionResult Contact()
		{
			ViewData["Message"] = "Your contact page.";

			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TuMvcApp/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Tu_Mvc.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Index.cshtml");
        }
	}
}

TuMvcApp/Views/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a asp-controller="Course" asp-action="Create" type="submit" class="btn btn-info">Create Course</a>

TuMvcApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Course</h1>
<a asp-controller="Courses" asp-action="Create" type="submit" class="btn btn-info">Create Course</a>

<h1>Categories</h1>
<a asp-controller="Categories" asp-action="Index" type="submit" class="btn btn-info">Categories List</a>
<a asp-controller="Categories" asp-action="Create" type="submit" class="btn btn-info">Create Categories</a>

TuMvcApp/Views/Categories/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<a asp-controller="Categories" asp-action="Index">Back to List</a>
<h2>Create Categories </h2>
@section Scripts
    {
    <script src="~/js/Categories/Categories.js"></script>
    <script>
        $(document).ready(function () {
            clearCategory();
            loadCategory();

        })
    </script>
}
<hr />

    <div id="formCreateCategory" class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <div>
                <ul id="validationSummary"></ul>
            </div>

            <div class="form-group">
                <label class="control-label">Name</label>
                <input id="Name" name="Name" class="form-control" />
            </div>

            @*Category*@
            <div class="form-group row">
                <label for="category" class="col-sm-12 col-form-label">Parent Category:&nbsp; (Select if you want to add as Subcategory)</label>
                <div class="col-sm-12">
                    <div id="category" class="dropdown">
                        <select id="ddCategory" class="form-control">
                            <option value="0" selected="selected"> Select</option>
                            <option value="1"> Category 1</option>
                            <option value="2"> Category 2</option>
                        </select>
                    </div>
                </div>
            </div>

            <input type="submit" id="formCreateCategory" onclick="CreateCategory(); return false;" value="Create" class="btn btn-primary btn-block" />
        </div>
    </div>

TuMvcApp/Views/Categories/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
    {
    <script src="~/js/Categories/Categories.js"></script>
    <script>
        $(document).ready(function () {
            LoadCategoriesIntoTable("tbl_index_all_categories");
        });
    </script>
}

<div class="container">
    <h2>Categories</h2>
    <a asp-controller="Categories" asp-action="Create" type="submit" class="btn btn-info">Create Category</a>
    <br />
    <hr />
    <table id="tbl_index_all_categories" class="display" style="width:100%">
        <thead>
            <tr>
                <th>id</th>
                <th>Name</th>
                <th>ParentId</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Loading..
                </td>
            </tr>
        </tbody>
    </table>

</div>

TuMvcApp/Views/Courses/Catalog.cshtml
@{
    ViewData["Title"] = "Catalog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
    {
    @*<script src="~/js/Courses/Categories.js"></script>*@
    <script>
        $(document).ready(function () {
            //LoadAllCourses("tbl_index_all_categories");
            LoadAllCourses();
        });

        function LoadAllCourses() {
            apiGetCategories = apiEndpoint + "/Courses"



            $.get(apiGetCategories)
                .done(function (courses) {
                    $('#courseCatalogContainer').empty();
                    $.each(courses, function (i, course) {
                        var item = `<div class="col-md-4">
                                                    <div class="card mb-4 addborder-on-hover">
                                                        <img class="card-img-top card-image" src="//placeimg.com/290/180/any" alt="Card image cap">
                                                        <div class="card-body">
                                                            <h5 class="card-title">${course.title}</h5>
                                                            <p class="card-text">${course.description}</p>
                                                            <a href="/" class="btn btn-dark btn-sm">Go somewhere</a>
                                                        </div>
                                                    </div>
                                                </div>`;
                        $('#courseCatalogContainer').append(item);
                    });
                })
                .fail(function (jqXHR, textStatus, errorThrown) {
                    swal({
                        title: "Error",
                        text: jqXHR.statusText,
                        icon: "error",
                        button: "Close",
                    });
                })

        }

    </script>
}
<h2>Catalog</h2>

<div id="courseCatalogContainer" class="container row">
    Loading..
</div>

TuMvcApp/Views/Courses/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
    {
    <script src="~/js/Categories/Categories.js"></script>
    <script src="~/js/Courses/Courses.js"></script>
    <script>
        $(document).ready(function () {

            clearCategory();
            ParentId
            loadCategory();

            initializeDatePickers();

            $('#ddCategory').on('change', function () {

                var selectedCategoryId = this.value;
                console.log("selectedCategoryId = " + selectedCategoryId);
                if (selectedCategoryId > 0) {
                    enableSelectSubcategory();
                    clearSubcategory();
                    loadSubcategory(selectedCategoryId);
                } else {
                    clearSubcategory();
                    addDefaultSelect("ddSubcategory", "Select Category First");
                    disableSelectSubcategory();

                }

            });
        })
    </script>
}
<div class="container">
    <h2>Create Courses</h2>

    <div class="row">
        @*first column*@
        <div class="col-md-6">
            @*Course Type*@
            <div class="form-group row">
                <label for="courseType" class="col-sm-3 col-form-label">Course Type:&nbsp;</label>
                <div class="col-sm-9">
                    <div id="courseType" class="dropdown">
                        <select id="ddCourseType" class="form-control">
                            <option value="0" selected="selected"> Select</option>
                            <option value="1"> Scorm</option>
                            <option value="2"> Non Scorm</option>
                        </select>
                    </div>
                </div>
            </div>
            @*Course Title*@
            <div class="form-group row">
                <label for="txtTitle" class="col-sm-3 col-form-label">Course Title:&nbsp;</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="txtTitle" placeholder="Enter title">
                </div>
            </div>
            @*Category*@
            <div class="form-group row">
                <label for="category" class="col-sm-3 col-form-label">Category:&nbsp;</label>
                <div class="col-sm-9">
                    <div id="category" class="dropdown">
                        <select id="ddCategory" class="form-control">
                            <option value="0" selected="selected"> Select</option>
                            <option value="1"> Category 1</option>
                            <option value="2"> Category 2</option>
                        </select>
                    </div>
                </div>
            </div>
            @*Subcategory*@
            <div class="form-group row">
                <label for="subcategory" class="col-sm-3 col-form-label">Subcategory:&nbsp;</label>
                <div class="col-sm-9">
                    <div id="subcategory" class="dropdown">
                        <select id="ddSubcategory" class="form-control">
                            <option value="0" selected="selected"> Select Category First</option>
                        </select>
                    </div>
                </div>
            </div>
            @*Description*@
            <div class="form-group">
                <label for="txtDescription">Description</label>
                <textarea class="form-control pull-right" id="txtDescription" rows="3"></textarea>
            </div>
            @*Start Date*@
            <div class="form-group row">
                <label for="dpStartdate" class="col-sm-3 col-form-label">Start Date:&nbsp;</label>
                <div class="col-sm-9">
                    <div class="form-group">
                        <div class="input-group date" id="dpStartdate" data-target-input="nearest">
                            <input id="txtStartdate" type="text" class="form-control datetimepicker-input" data-target="#dpStartdate" />
                            <div class="input-group-append" data-target="#dpStartdate" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @*End Date*@
            <div class="form-group row">
                <label for="dpEnddate" class="col-sm-3 col-form-label">End Date:&nbsp;</label>
                <div class="col-sm-9">
                    <div class="form-group">
                        <div class="input-group date" id="dpEnddate" data-target-input="nearest">
                            <input id="txtEnddate" type="text" class="form-control datetimepicker-input" data-target="#dpEnddate" />
                            <div class="input-group-append" data-target="#dpEnddate" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @*Duration*@
            <div class="form-group row">
                <label for="txtDuration" class="col-sm-3 col-form-label">Duration:&nbsp;</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="txtDuration" placeholder="Enter duration">
                </div>
            </div>
        </div>
        @*second column*@
        <div class="col-md-6">
            @*Published By*@
            <div class="form-group row">
                <label for="txtPublishedBy" class="col-sm-3 col-form-label">Published By:&nbsp;</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="txtPublishedBy" placeholder="">
                </div>
            </div>

            @*Access Mode*@
            <div class="form-group row">
                <label for="accessMode" class="col-sm-3 col-form-label">Access Mode:&nbsp;</label>
                <div class="col-sm-9">
                    <div id="accessMode" class="dropdown">
                        <select id="ddAccessMode" class="form-control">
                            <option value="0" selected="selected"> Select</option>
                            <option value="1"> Internal</option>
                            <option value="2"> External</option>
                        </select>
                    </div>
                </div>
            </div>

            @*Course Image:*@
            <div class="form-group row">
                <label for="txtCourseImage" class="col-sm-3 col-form-label">Course Image:&nbsp;</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="txtCourseImage" placeholder="Select An Image">
                </div>


            </div>
        </div>

    </div>
    <input type="submit" id="formCreateCategory" onclick="CreateCourse(); return false;" value="Create" class="btn btn-default" />

</div>

TuMvcApp/Views/Courses/Search.cshtml
@{
    ViewData["Title"] = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts  {
    <script src="~/js/Courses/Courses.js"></script>
    <script>

        $(document).ready(function () {

            loadSearchResult();

        });
    </script>
}
    <h2>Search Result for <i> "@Context.Request.Query["q"]"  </i></h2>

<div id="courseCatalogContainer" class="container row">
    Loading..
</div>

TuMvcApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TuMvcApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TuMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Home</h1>

TuMvcApp/Views/Index.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tu_Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/landingpage.css" />

       
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/landingpage.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-transparent">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="btn btn-outline-primary btn-sm" asp-controller="Auth" asp-action="signin" asp-route-returnUrl="@Context.Request.Query["returnUrl"]">Login</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container h-75 ">
        <div class="row h-75 justify-content-center align-items-center m-5">
            @*<img src="~/images/logo.png" alt="Alternate Text" width="50%" />*@
            <h1><b>T:University</b></h1>

            <div id="frmSearchCourse" class="col-12 ">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" id="txtSearch" placeholder="Search Course" onkeypress="detectEnterKey(event)" >
                </div>
            </div>
        </div>
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function detectEnterKey(e) {
            if (e.keyCode == 13) {
                var searchString = $("#txtSearch").val().trim();
                searchCourse(searchString);
            }
        }
    </script>
</body>
</html>

TuMvcApp/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tu_Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        @*<link rel="stylesheet" href="~/lib/spin-js/spin.css" />*@
        <link rel="stylesheet" href="~/lib/tempusdominus-datepicker/tempusdominus-bootstrap-4.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @RenderSection("styles", false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand" href="/"><img src="~/images/logo.png" alt="Alternate Text" width="300px" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="form-inline my-6 my-lg-0 input-group w-50">
                <input id="txtSearch" class="form-control border-radius-0 border-right-0" type="search" placeholder="Search" aria-label="Search" onkeypress="detectEnterKey(event);">
                <div class="input-group-append">
                    <button class="btn border bg-transparent border-left-0 border-radius-0 cursor-pointer" onclick="searchClick();">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
            &nbsp;
            &nbsp;
            &nbsp;
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Courses" asp-action="Catalog"> <i class="fas fa-list"></i> Course Catalog</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-chart-bar"></i> Dashboard
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="nav-link" href="#"> Learner</a>
                        <a class="nav-link" asp-controller="Admin" asp-action="Index"> Admin</a>
                    </div>
                </li>
            </ul>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container container-lg body-content">
        @RenderBody()


    </div>
    @*<footer class="bg-dark">
            <p class="text-white">&copy; 2019 - Tu_Mvc</p>
        </footer>*@


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        @*<script src="~/lib/spin-js/spin.js"></script>*@
        <script src="~/lib/sweet-alert/sweetalert.min.js"></script>
        <script src="~/lib/momentjs/moment.js"></script>
        <script src="~/lib/tempusdominus-datepicker/tempusdominus-bootstrap-4.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>

    <script>
        var apiEndpoint = "@Configuration["ApiEndpoint"]";

        var searchString;

        function searchClick() {
            debugger;
            searchString= $("#txtSearch").val().trim();
            searchCourse(searchString);
        }

        function detectEnterKey(e) {
            if (e.keyCode == 13) {
                searchString = $("#txtSearch").val().trim();
                searchCourse(searchString);
            }
        }
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>